### ISSUE TITLE
Thank you - and a quick question

### ISSUE THREAD

**Issue by voarsh** [Ghostcrawler336/trinityadmin#20]
Just want to say thanks firstly!

There are a few tabs like Ah bot (?), who, event, etc that have no content/functionality in them. Are they a work in progress? are you still working on this at all? 

There are surprisingly no admin tools out there for Trinity and would appreciate it if it was maintained! :)

Thanks.

**Comment by Ghostcrawler336** [comment]
Hello,

Sorry about getting back to you so late. I must have missed this... I was under impression this was working, I'll double check it when I get the chance and fix what's broken. Thasnk you. :+1:

**Comment by voarsh** [comment]
Oh great. :)

Do you want me to give you a full list of things I find not working? (Including commands not found?) With screenshots?

**Comment by Ghostcrawler336** [comment]
Yeah that would be very helpful, so I'll know what to test and fix! :)

**Comment by voarsh** [comment]
Hi.

Here's some simple screenshots of issues from the LATEST (I mean LATEST builds of TrinityCore) :).
![ahbot-blank](https://cloud.githubusercontent.com/assets/10189051/8514701/2db2d634-238d-11e5-93b2-4383695b63d8.png)
![event-blank](https://cloud.githubusercontent.com/assets/10189051/8514702/2db5c286-238d-11e5-9d78-b4b53fe8ebe8.png)
![pvp-blank](https://cloud.githubusercontent.com/assets/10189051/8514703/2dbc19e2-238d-11e5-86d8-c7540458db01.png)

I am not sure what these functions do. Are you able to explain what they do? (if you don't mind?) :smile: 

PS. This is on 3.3.5 - I am not sure if you plan on supporting X6. That's too adventurous for me...

**Comment by Ghostcrawler336** [comment]
Hello, sorry about getting back to you so late... I'm actually not to sure what those tabs do, as they have never worked even before I decided to update this addon. So can't help you to much on that. :/ And I had thoughts about updating this for x6, but haven't set any dates yet.
